import Head from "next/head";
import { Inter } from "next/font/google";
import Home from "@/components/Home/Home";
import AboutMe from "@/components/AboutMe/AboutMe";
import Services from "@/components/Services/Services";

const inter = Inter({ subsets: ["latin"] });

export default function MainIndex() {
  return (
    <>
      <Head>
        <title>Jennifer Simmons LSCSW</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <AboutMe />
      <Services />
    </>
  );
}
